
server:
  # server port 8181
  port: 8484
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

# logconfig
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# userconfig
user:
  password:
    maxRetryCount: 5
    lockTime: 10

# Springconfig
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booksystem?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    password: root
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # resource
  messages:
    # Internation file
    basename: i18n/messages

# tokenconfig
token:
    # tokenflag
    header: Authorization
    # token secret
    secret: abcdefghijklmnopqrstuvwxyz
    # token timelong
    expireTime: 30000
  
# MyBatis config
mybatis:
  # search package name
    typeAliasesPackage: com.example.capgeminitestbackend.entity
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

springfox:
  documentation:
    swagger-ui:
      enabled: true
# swagger3
spring.mvc.pathmatch.matching-strategy: ant_path_matcher

